### ISSUE TITLE
setTubeSize setWeaponTubeSize in SpaceShip

### ISSUE THREAD

**Issue by StarryWisdom** [daid/EmptyEpsilon#1025]
Due to me not noticing when adding the scripting for setTubeSize that there was setWeaponTubeSize there are now 2 functions in SpaceShip doing the same thing (same with getTubeSize and getWeaponTubeSize)

probably one should wrap around the other along with some sort of decision on scripting - setWeaponTubeSize is consistent with other tube functions, setTubeSize is consistent with ShipTemplate:setTubeSize.

Obviously if there is any script change compatibility should be considered.

**Comment by oznogon** [comment]
For context:

- PR #933 added the current `get`/`setTubeSize` to `spaceShip`
- PR #679 added `get`/`setWeaponTubeSize` to `spaceShip`, as well as `setTubeSize` to `shipTemplate`

For reference, this is what `setTubeSize` in `shipTemplate` looks like: https://github.com/daid/EmptyEpsilon/blob/02d9ab304ad058b530df94985f18de08537cf5c7/src/shipTemplate.cpp#L189-L194

--

In `spaceShip`, the only functional difference between `setWeaponTubeSize`: https://github.com/daid/EmptyEpsilon/blob/2cfcdeb76ff13eaf12512baacc388cef62d3e9bb/src/spaceObjects/spaceship.cpp#L1231-L1236

and `setTubeSize`: https://github.com/daid/EmptyEpsilon/blob/2cfcdeb76ff13eaf12512baacc388cef62d3e9bb/src/spaceObjects/spaceship.cpp#L1268-L1273

is the index range limit.

- `setWeaponTubeSize` uses `weapon_tube_count`, which is pulled from the ship template and recalculated when `setWeaponTubeCount` is called
- `setTubeSize` uses `max_weapon_tubes`, a static constant of 16 set in [shipTemplate.h](https://github.com/daid/EmptyEpsilon/blob/02d9ab304ad058b530df94985f18de08537cf5c7/src/shipTemplate.h#L12)

`weapon_tube_count` seems like the better choice in `spaceShip` since a limit of `max_weapon_tubes` could match a tube that doesn't exist, and `setWeaponTubeCount` is called when importing from the ship template. The `weapon_tube_count` should be changed only through calling `setWeaponTubeCount` anyway; otherwise, something else needs work.

--

Only `get`/`setTubeSize` is exposed to scripting in `spaceShip`: https://github.com/daid/EmptyEpsilon/blob/2cfcdeb76ff13eaf12512baacc388cef62d3e9bb/src/spaceObjects/spaceship.cpp#L98-L101

`setTubeSize` is also what's exported: https://github.com/daid/EmptyEpsilon/blob/2cfcdeb76ff13eaf12512baacc388cef62d3e9bb/src/spaceObjects/spaceship.cpp#L1438-L1441

and it's what `shipTemplate` uses.

So whatever the preferred `get`/`set` method does, it should be called `setTubeSize` to maintain consistency with existing scripts as well as `shipTemplate` behavior.

One point against naming it `setTubeSize`: most other Lua-exposed tube-related functions are prefixed `setWeaponTube...` instead of `setTube...`.

--

The getters also need reconciliation:

`getWeaponTubeSize`: https://github.com/daid/EmptyEpsilon/blob/2cfcdeb76ff13eaf12512baacc388cef62d3e9bb/src/spaceObjects/spaceship.cpp#L1224-L1229

`getTubeSize`: https://github.com/daid/EmptyEpsilon/blob/2cfcdeb76ff13eaf12512baacc388cef62d3e9bb/src/spaceObjects/spaceship.cpp#L1275-L1280

There are two differences: the `weapon_tube_count`/`max_weapon_tubes` difference, and the default value on an invalid index. `getWeaponTubeSize` returns a default of MS_Small, and `getTubeSize` returns a default of MS_Medium.

It seems like MS_Medium would be the intended/preferred default, if the function should return any default value at all. The Lua param-to-enum conversion in `missileWeaponData.hpp` defaults to MS_Medium, for example: https://github.com/daid/EmptyEpsilon/blob/8f23b2f4c2a50ddebd8e383024cbf15193d924fc/src/missileWeaponData.hpp#L56

--

So it seems like the fix that would disrupt existing Lua scripts the least would be to:

- Because they aren't exposed to Lua, either deprecate `get`/`setWeaponTubeSize` and have them just pass values to `get`/`setTubeSize`, or remove `get`/`setWeaponTube` altogether since it looks like they aren't used elsewhere in the code
- Use `weapon_tube_count` instead of `max_weapon_tubes` in `get`/`setTubeSize`, for consistency with current `get`/`setWeaponTubeSize` behavior
- Use MS_Medium as the default value returned by `getTubeSize` instead of MS_Small, for consistency with the `missileWeaponData` enum conversion default

If anything relies on the behavior of `getTubeSize` returning MS_Small on an index beyond the tube count limit (I suspect the tweak screen might?), it should also be updated.
