### ISSUE TITLE
bug: rendered text nearly unreadable

### ISSUE THREAD

**Issue by Piglit** [daid/EmptyEpsilon#1031]
On some laptops the text displayed on radarView of science and relay appears very pixelated and is not readable.

AutoRadarRotation was used, and it only occured on some machines.

**Comment by BennyTheBen** [comment]
I've experienced this on a few laptops recently. It makes Science and relay pretty unplayable on affected machines because you can't read the text and give bearings to Helm etc.
The issue is present regardless of whether FSAA is on or off. Screenshot to come when I get time. Is there any info I could provide to help you resolve this more easily?

**Comment by BennyTheBen** [comment]
I think there's a typo in the issue name: please correct 'test' to 'text'.

**Comment by BennyTheBen** [comment]
![emptyepsilonbug](https://user-images.githubusercontent.com/4335626/97337927-c4b0df00-1878-11eb-914c-51641bcd9901.PNG)

**Comment by daid** [comment]
The radar is first rendered to a texture, and then that texture is rendered to the screen. The code tries to make this texture 1:1 size with your screen. But in this case it seems it failed.

What do you have as DPI setting in windows? (in display settings)
![image](https://user-images.githubusercontent.com/964186/98348408-ffeda380-2018-11eb-85d4-f4bb49db4f84.png)
Maybe that is related?

**Comment by Crewrow** [comment]
![CAM_20201114_201847](https://user-images.githubusercontent.com/34844254/99155349-6e84ce00-26b7-11eb-8c50-2892b3298cf4.jpg)


I have the same problem with my Lenovo ThinkPad X230 and X230T

**Comment by BennyTheBen** [comment]
Windows display scaling is on 100% (recommended) for me too.

**Comment by gcask** [comment]
From a quick series of test: the core of the issue appear to stem from the resolution dropping below the 'virtual size' from the window manager.

When that happens, the texture created in `GuiElement::adjustRenderTexture` drops at 1k (or below) whereas otherwise it will create a 2k texture.

A quick and dirty fix would be to always create a texture with a minimum 2k size.

Additionally I have found that, in the same function, always setting a viewport of `(0, 0, 1, 1)` seemed to lead to acceptable results - even leaving the texture at 1k.

I have tried this with multiple ratios without seeing any artifacts, although I wouldn't rule them out (I'm assuming the viewport was set the way it is for a reason!)

**Comment by daid** [comment]
It's trying to setup a render to texture so that it's 1:1 pixels for the texture and what is drawn to the screen. But it's most likely not doing it correctly seeing this bug...

**Comment by pixelclef** [comment]
Discovered an oddity probably related to this issue.

When selecting only Science, the render is poor.
When selecting Engineering and Science, the render is better.
![just-science](https://user-images.githubusercontent.com/7457571/111516252-b24d1a00-8721-11eb-9001-ff3e64eea19e.png)
![engineering-science](https://user-images.githubusercontent.com/7457571/111516263-b4af7400-8721-11eb-8f65-5407e5c923c7.png)

**Comment by gcask** [comment]
Investigation notes:
I've set my screen to 1366x768, and disabled the sprite texture rect / scaling in `drawRenderTexture()`.
Having the window in 4:3 I see something reasonable:
![image](https://user-images.githubusercontent.com/53709079/111633790-41af0780-87cc-11eb-9f0e-30ca56ed3c73.png)

As soon as I go fullscreen, texture aspect ratio are off.
![image](https://user-images.githubusercontent.com/53709079/111633843-4ecbf680-87cc-11eb-818e-882494b45b8f.png)

Resizing the window, there's definitely one cutoff point where it goes from working OK to messed up:
![image](https://user-images.githubusercontent.com/53709079/111634263-b97d3200-87cc-11eb-93c9-bc07315ddcd8.png)
![image](https://user-images.githubusercontent.com/53709079/111634321-c732b780-87cc-11eb-960b-3ab76b0b8b5c.png)

(the window size barely changed between these two).

When I get more free time I'll look at exactly what happens around that cutoff point.
