### ISSUE TITLE
windows log file is unreliable

### ISSUE THREAD

**Issue by StarryWisdom** [daid/EmptyEpsilon#1042]
The windows log file has a tendency to stop mid word a while EE is running and in the case of a crash wont finish writing it.

I expect its due to not flushing the buffer or related, but this is untested.

**Comment by oznogon** [comment]
This is on the SeriousProton end: https://github.com/daid/SeriousProton/blob/master/src/logging.cpp#L63

Per https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setvbuf?view=vs-2019#remarks the issue seems to be a lack of support for line buffering in Windows:

```
_IOLBF | For some systems, this provides line buffering. However, for Win32, the behavior is the same as _IOFBF - Full Buffering.
```

Since Windows doesn't support line buffering, the logs can't be made to flush after each log line. The closest solution might be to either switch to no-buffer (`_IONBF`) which will probably be a performance hit, or to define a small buffer size, which means the log will still get cut off on a crash but won't lose as much information. (The default stream buffer size in win32 appears to be 4k.)
