### ISSUE TITLE
windows release zip and logs folder

### ISSUE THREAD

**Issue by StarryWisdom** [daid/EmptyEpsilon#1054]
If there is a logs folder then empty epsilon will make log files for each time its started (rather than overriting them all).

Currently the windows zip is lacking such a folder.

If this is not intentional it would be nice if it was added.

**Comment by oznogon** [comment]
Nope, that's for the JSON game-event logs used by the viewer in the repo's `/logs/index.html` (which also isn't bundled in the windows zip).

When that folder's present, you see this line in EmptyEpsilon.log (which stays in the same place and is still overwritten every run):

```
[INFO]  Opened game state log: logs/game_log_07-09-2020_10.41.22.txt
```

When it's not present, you see this line in the log:

```
[WARN]  Failed to open game state log file: logs/game_log_07-09-2020_10.44.36.txt
```

That game logging feature should probably be disabled by default and enabled in options, instead of enabled by default but not generating anything out of the box because the folder doesn't exist.

**Comment by NinjaSpectre** [comment]
These game logs get rather large in size as well since it tries to document the actions of every object.  Wouldn't take overly long before some users became mystified as to where their hard drive space went if this was defaulted on.

**Comment by daid** [comment]
It is intentional that this is not created by default.
