### ISSUE TITLE
Location of `scriptstorage.json` and `options.ini` 

### ISSUE THREAD

**Issue by capt-t** [daid/EmptyEpsilon#1090]
At least on Windows, `scriptstorage.json` is created in a location (namely the game directory) different from `options.ini` (can be in the `.emptyepsilon` directory in the user directory).

**Comment by oznogon** [comment]
macOS: `/EmptyEpsilon.app/Contents/Resources/scriptstorage.json`

No path given when opening `scriptstorage.json`: https://github.com/daid/EmptyEpsilon/blob/8ce7d385f36c5936f9aeba3104b4ce0e89634b0c/src/scriptDataStorage.cpp#L9-L46

`options.ini` determines if there's a `HOME` environment variable and modifies its behavior if so. Otherwise it passes no path: https://github.com/daid/EmptyEpsilon/blob/60af880b9fc5094f68c94e47e076339dfc921676/src/main.cpp#L109-L112

https://github.com/daid/EmptyEpsilon/blob/60af880b9fc5094f68c94e47e076339dfc921676/src/main.cpp#L341-L356

**Comment by oznogon** [comment]
cf. #1054
