### ISSUE TITLE
Crash with commsFunction from required file

### ISSUE THREAD

**Issue by capt-t** [daid/EmptyEpsilon#1170]
Set `station:setCommsFunction(commsFunc)` with `commsFunc` from a `require`d file.

Then EE always crashs as soon as the communication is established.

**Comment by daid** [comment]
The crash happens here:
https://github.com/daid/EmptyEpsilon/blob/master/src/commsScriptInterface.cpp#L77
As `getScriptObject()` is `nullptr`

The actual problem is in the `require()` function, the problem is actually if you:
`print(_G, _ENV)` on the main scenario scripts, you'll see that they are different
But if you do the same in the `require`d file then you'll notice that they are the same, which is unintentional.
