### ISSUE TITLE
database class names sometimes not being translated

### ISSUE THREAD

**Issue by StarryWisdom** [daid/EmptyEpsilon#1274]
in the comments of #1240 muerteFR said that some ship database classes where being duplicated when translated - one copy in the client language and without translation

(screenshots are in that thread)

the entries I saw issues with had their class set via setClass(_("class","something")) rather than setClass(_("something")) which was used for the entries with no issues

I currently don't understand the locale tools to check if they are translated, likewise I don't speak a second language enough to make testing easy.

**Comment by aBlueShadow** [comment]
As we figured out (thanks to starry and daid), it seems that the issue was introduced with #1269, as some ships now have a "class"  context in their translation, and some don't. As the frigate and starfighter entries did not exist with the class context yet, the split happened.

Solution: 
- Update the en.po: in your build directory, do a `make update_locale` (or `ninja update_locale` if you use ninja instead of make)
- in poedit, update your translation file from a template (it wants a pot-file instead of po, you change the file type to .po, then choose the newly re-generated en.po)
- poedit should now suggest the new class translations with the "class" context, as they are guesses from the programm, there are marked yellow. confirm these accordingly, then save the file

**Comment by muerteFR** [comment]
@daid This issue can possibly be closed?
