### ISSUE TITLE
[Problem] Scenarios: title translation and comments do not work

### ISSUE THREAD

**Issue by muerteFR** [daid/EmptyEpsilon#1387]
The translation of titles and descriptions of the scenarios does not work.
The scenario text itself works well.
I tried with the 3 scenarios with an existing en.po: waves, Beacon and Edge of space.
I saw that the title and description translation system is different from usual.
Is it being tested?
Thanks

--- Scenario
-- @script scenario_05_beacon

**Comment by gcask** [comment]
Seeing as even more info is coming from those now, here are a couple ideas (none of them being ideal):

A cheap version (for translators) would be to simply add `tr("...")` tag for each line, let xgettext pick them up and handle the added `tr("")` tags on the C++ side.
Caveat is having one tr per line, which is a little awkward + the handling on the C++ side.

To maintain some sense of sanity we could also leverage [lua multiline comments](https://www.lua.org/pil/1.3.html) with a specific mark of our choosing + a `tr()` inside it.

Another one would be to have a dedicated tool that knows how to parse the metadata, and spit out something xgettext can understand.
Then in the C++ side, it's just a matter of `tr()-ing` the value with the right context.
Caveat is obviously having a new tool in the pipeline.

There may be other options too.

**Comment by daid** [comment]
> Another one would be to have a dedicated tool that knows how to parse the metadata, and spit out something xgettext can understand.

That is already in place: https://github.com/daid/EmptyEpsilon/blob/master/update_scenario_locale.py#L35

The problem is purely at the C++ side, the localization file for a scenario is loaded after a scenario is selected, so during scenario selection the code doesn't know about the translated strings yet. It's on my todo list to fix this (and make the scenario options translatable as well)

**Comment by muerteFR** [comment]
![tutos](https://user-images.githubusercontent.com/61491656/140970636-36e2f41f-faf6-4ee2-98ed-23ca68795fcb.jpg)

The problem is also encountered in translating the text and names of different tutorials without video.

**Comment by muerteFR** [comment]
@daid, can this problem be closed or do I add the following issue Or else I create another issue for that :

Now that the titles and descriptions of the scenarios are translatable, how do you create the en.po files for the scenarios that do not contain any translation tags? Can we add an "empty" tag or one that we will not translate, only to be able to create the corresponding en.po? A bit like the temporary solution proposed some time ago to allow translatable audio files.

**Comment by daid** [comment]
Don't think this is done yet. The move in https://github.com/daid/EmptyEpsilon/pull/1615 shouldn't be needed for example, so that's clearly still a bug somewhere. And scenario options aren't setup for translations yet.

**Comment by daid** [comment]
As for your other remark about scenarios without any translation flag. The python script does generate a .po file for them, but then removes it if it finds that the lua script has no other translatable strings. Under the assumption that if there are no other strings, it's not setup for translation yet.
I did that because I figured a scenario without translation markers should not have the title/description translated, and scenarios without any extra text ingame would be odd, and not really a complete scenario.

**Comment by muerteFR** [comment]
Yes I tested by manually adding the en.po file and I saw that it deleted it.

So, for the case of empty text scenarios like Surrounded and Empty spacebut which still deserve to have the translation of the presentation, iss it possible to add just a sentence or 2 like in Training1 or Waves for example to solve this problem?

**Comment by daid** [comment]
The surrounded scenario could use a simple "start text" like Basic has, where you get an initial transmission explaining what to do.

Not sure what to do with empty, as it mostly exists as a blank slate for the GM screen.

**Comment by daid** [comment]
I think the translations work now so this can be closed?
