### ISSUE TITLE
BUG: Vertical offset display glitch for player stations when Warp active in Windowed mode (not replicated for Fullscreen or default resolution)

### ISSUE THREAD

**Issue by Wrongtown** [daid/EmptyEpsilon#158]
When warp is activated the display elements are offset towards the top of the window. The smaller the window is compared to your screen resolution, the worse this effect is. The effect does seem to be present during Jump Drive activation but is far less jarring given the intention effects already in play.

_Steps to Replicate_
1. Toggle Fullscreen OFF (OR Toggle Fullscreen to OFF, close program and re-launch).
2. Set window to a different resolution than the default. The more you change this, the more apparent the issue is.
3. Log in to a scenario as Helm and any other positions you care to take on a ship that has Warp drive (or set Warp drive available).
4. Engage Warp

Video of testing [here](https://www.dropbox.com/s/j3vn5qkyae3pop4/Video_2016-04-02_013434.wmv?dl=0).

**Comment by Wrongtown** [comment]
Updated steps to replicate.

If the window size is not changed at all this does not occur, so basically it would seem that trying to render the stations at anything other than default resolution is the root cause?

**Comment by JonathanILevi** [comment]
This bug occurs when the window is resized after warp is used for the first time.  The bug effects both vertical and horizontal in proportion to the change of the window size.  (Hence, why you have not reproduced the bug in full-screen.

The problem is that the warp post process shader is given the `inputSize` only the first time it is used.

[Because of this line.](https://github.com/daid/SeriousProton/blob/master/src/postProcessManager.cpp#L45)
With this if condition removed the bug is fixed.  I recommend either removing the if or adding a condition for when the screen size has been changed.

@daid
