### ISSUE TITLE
[Issue Localisation scenarios with audio] cannot be broadcast in a language other than EN.

### ISSUE THREAD

**Issue by muerteFR** [daid/EmptyEpsilon#1704]
Currently the sounds (.ogg) of the scenarios cannot be heard in a language other than EN.
For example, if the 51_Deliver_Ambassador scenario is played in French, English sounds will be heard.

A solution had been proposed while waiting for something better: add translation tags on these ogg files to be able to redirect them to the right files with the translation. (sa_51_Gremus1.ogg --> sa_51_Gremus1_fr.ogg)

Can we reapply this method temporarily while waiting for a better solution?

**Comment by daid** [comment]
Change 083a193 will make it so that if a scenario does:
`playSoundFile("audio/scenario/51/sa_51_Michael.ogg")`
It will first try to play `audio/scenario/51/sa_51_Michael.fr.ogg` and if that doesn't exist it will play `audio/scenario/51/sa_51_Michael.ogg`
That should allow for localization with proper english backup.
