### ISSUE TITLE
Relay text flashes in the upper left hand corner

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#1735]
When opening comms with a station, the text flashes in the upper left hand corner of the screen before being placed in the appropriate location within the pop-up dialog box. 2022.03.16 release

**Comment by daid** [comment]
I assume this is a one frame flash?

The reason for this is that visibility and sizes are changed during drawing, example:
https://github.com/daid/EmptyEpsilon/blob/master/src/screenComponents/commsOverlay.cpp#L148

The fix is easy, it's just moving that logic from `onDraw` to `onUpdate`. As onUpdate is done before layouting, and draw is after layouting.

**Comment by Xansta** [comment]
I think it is a one frame flash. It's not a big deal, just a bit distracting
