### ISSUE TITLE
Hotkey: Set science scan parameter directly

### ISSUE THREAD

**Issue by daid** [daid/EmptyEpsilon#1770]
For joystick bindings it is nice to have a binding that sets the analogue value directly to the scan parameter value.

**Comment by TheSkywise** [comment]
This issue is very important to me. I built a custom controller that has the four science parameters mapped to four different knobs. With the new version, this controller is obsolete. Any help would be awesome to allow binding analog values to the scan parameter values.

**Comment by aBlueShadow** [comment]
In the meantime, you could make that controller still work, if you you can reprogram it in a way to send those knob values to the integrated [http-server](https://github.com/daid/EmptyEpsilon/wiki/HTTP-Server)

**Comment by TheSkywise** [comment]
I am looking at the http-server and I guess I understand the basic concept. You can send all sorts of commands from client to the http-server, including the analog values for the scan parameter...

I just can't figure out how to make it work.

**Comment by aBlueShadow** [comment]
That depends on the specific microcontroller that you are using for the custom controller. If you have a chip that is directly capable of WLAN communication (like Raspberry Pi Pico W oder some ESP-based chip), you could send the http commands directly from the chip instead of emulating joystick axes.
If not, that would be more tricky, as you would need either extra hardware or some piece of software on your computer that is translating the incoming keypresses to http commands. That could be a small script or a local website that is listening for key presses. Or maybe even listening for joystick input, I don't know if this is possible via HTML5
