### ISSUE TITLE
REQUEST: Allow paste to work in server address field.

### ISSUE THREAD

**Issue by MyrddinE** [daid/EmptyEpsilon#188]
Manually typing a server IP (multiple times per night due to the current instability of the system) is very tedious. The ability to auto-populate the last IP used, or allow paste, would be greatly appreciated.

**Comment by daid** [comment]
Done. Note that the next version also allows you to publish your server on the internet (with password protection) so that will help.

But I'm more interested in the instability. I know there is a keyboard input related crash that I've not been able to track down 100%.
If you run the windows version, and have crashes, I'm very interrested in the .RPT files that the game generates then, as they help me track down crashes.
