### ISSUE TITLE
Internally docked ship's label is still visible on carrier ship's helms radar

### ISSUE THREAD

**Issue by hemmond** [daid/EmptyEpsilon#1904]
I've noticed, that you still see callsigns of all internally docked ships on Helms radar (positioned where your callsign would be). Not sure if this is desired behaviour. Big carriers might have problem with this.

Oznogon's Discord response: 
Looks like internal docking is kind of a hack; the ships still exist in-world at the carrier's coordinates, they're just not rendered on radars or 3D views. So it's probably an oversight.

**Comment by oznogon** [comment]
`GuiRadarView::drawObjects` draws callsigns. Objects are determined to be visible if they're not obscured by fog-of-war (nebula obstruction on short-/long-range radar, outside of friendly/probe short-range radar on Relay). Then if callsigns are being shown on this radar type, and the object has a callsign, it's rendered:

```cpp
            if (show_callsigns && obj->getCallSign() != "")
                renderer.drawText(sp::Rect(object_position_on_screen.x, object_position_on_screen.y - 15, 0, 0), obj->getCallSign(), sp::Alignment::Center, 15, bold_font);
```

Could extend that check to confirm the object's docking status. `obj` is a SpaceObject, and while the `DockStyle` enum is in SpaceObject, there's no check for an object's current DockStyle except in the `docked_style` param on SpaceShips. So we could move `docked_style` up into SpaceObject or have a separate condition if obj is a SpaceShip.

A more complete solution might be for carriers to maintain a list of internally docked objects. RadarView could then exclude those from `visible_objects` instead of having `if (docked_style == DockStyle::Internal) return;` checks in SpaceShip `drawOnRadar` (and other similar checks for things like `SpaceShip:drawOnGMRadar`, `SpaceShip:draw3D`, and collision data). That'd also solve the problem of getting a list of all ships docked with a carrier.
