### ISSUE TITLE
[GUI] GM comms chat spawns minimised with regular size. 

### ISSUE THREAD

**Issue by hemmond** [daid/EmptyEpsilon#1923]
On GM screen when previous comms chat was closed while in minimised state, next chat opens half-"minimised" (minimise button is lit, text fields are missing), but still appears with the default size (as a normal GM chat comms box). 

I believe it should either: 

1. Forget close status after closing the chat (and thus next chat will show with fields and minimise button not toggled)
2. Open chat in minimised state, but then it should show up in minimised dimensions. 

Honestly I think option 1 should be correct, since outgoing GM chats still needs to specify as whom GM will be hailing and contents of incomming chats will be important for GM anyways pretty soon. So I'd recommend upon GM comms chat closure to reset minimised status to false. 

Tested on current Master.

**Comment by oznogon** [comment]
Specific reproduction:

1. Open master build as a server.
2. Open GM screen on server.
3. On the GM screen, add a player ship and a CPU ship.
4. On the GM screen, enable "Intercept all comms".
5. Open master build as a client.
6. Connect the client to the server.
7. On the client, select the player ship, then the Relay crew screen.
9. On relay, open comms to the CPU ship.
10. On the server GM screen, minimize the chat.
11. On the server GM screen or player, close the chat.
12. On the client Relay screeen, open comms with the CPU ship again.

Observed behavior:

![image](https://user-images.githubusercontent.com/19192104/222581953-b66e3c32-319b-44e4-bd22-b53048070f1e.png)

Clicking the minimize button while in the inconsistent state corrects the display as expanded with text as expected.

Expected behavior:

Either @hemmond's 1:

![image](https://user-images.githubusercontent.com/19192104/222583017-d5b80f74-f72d-4e72-be0c-776ed601c86f.png)

or 2:

![image](https://user-images.githubusercontent.com/19192104/222583064-fce16fbc-5bf3-46b9-b3ba-607e73277708.png)

**Comment by hemmond** [comment]
Yes, thanks for the screenshots and reproducibility scenario. I did these steps to reproduce:

1. Open master build as a server.
2. Open GM screen on server.
3. On the GM screen, add a player ship
4. Select player ship and hail it. 
5. Minimize the chat.
6. Close the chat.
7. Select player ship and hail it again

(probably shorter, needs only one EE instance and only GM screen)
