### ISSUE TITLE
EE-2023.06.17 Navy Striker model super-sized

### ISSUE THREAD

**Issue by CurePindal** [daid/EmptyEpsilon#1997]
Issue: In the current release version the Navy Striker is larger than the capital ships.
Expected: Fighter sized

**Comment by Xansta** [comment]
The Striker is in the file where deprecated ships live (OLD.lua). The ships in this file are kept around for backwards compatibility reasons. Some other player ships in this file have been hidden from typical use by adding the `hidden()` directive to their templates. These include the Player Cruiser, the Player Missle Cr., the Player Fighter. The non-player ship Fighter has also been hidden. Hiding these templates makes them accessible only to scenario scripts.

The current form of Striker might also be a candidate for being hidden. There are some users that like the Striker if its base impulse speed is improved just because they like the appearance of the 3D model. To shrink the model down to a size that is more consistent with the other models in the game is another way to fix this issue.

It's easy to hide the template. It's more difficult to shrink the model. This particular issue has been around for many versions and was not introduced with version 2023.06.17

**Comment by oznogon** [comment]
> It's more difficult to shrink the model.

Might not be. The model data has a setScale function.

If "Navy Striker" refers to the Striker template, then it looks like the model is `dark_fighter_6`: https://github.com/daid/EmptyEpsilon/blob/9b40e88103071005a28db9b50a02170a5fa47e3c/scripts/shiptemplates/OLD.lua#L305C163-L305C177

Here's that model's setScale line: https://github.com/daid/EmptyEpsilon/blob/9b40e88103071005a28db9b50a02170a5fa47e3c/scripts/model_data.lua#L112

**Comment by Xansta** [comment]
If you change the value in `setScale()`, would it need to be larger or smaller? I see other values in the file such as 20, 3, 6, 8, etc. If the value were to change, would there need to be corresponding changes to the entries for `addBeamPosition()` and `addEngineEmitter()`?

**Comment by oznogon** [comment]
I changed that line's setScale value to 1 and the thrust emitters, weapons point locations, arcs, etc. all scaled with it.

Setting it to 1 resulted in this:

![Snapshot_2023-10-20_14-00-29](https://github.com/daid/EmptyEpsilon/assets/19192104/d1f49f57-adfb-48c4-a543-8978819d09c0)

Setting it to 10 resulted in this:

![Snapshot_2023-10-20_14-04-34](https://github.com/daid/EmptyEpsilon/assets/19192104/44af38f3-058a-419e-ba86-2690a2ad68c3)

**Comment by oznogon** [comment]
There are different values across the file because the models' geometry is different across sources, artists, purposes. Also why there's a setRenderOffset function in for ModelData, because they don't all have the same origin point either.

Those functions allow the models to be relatively normalized and adjusted without needing to edit the model geometry in Blender or what have you.

**Comment by Xansta** [comment]
See merged pull request #2024
