### ISSUE TITLE
Feature: Player ship stats in ship selection screen and database

### ISSUE THREAD

**Issue by CurePindal** [daid/EmptyEpsilon#1998]
I couldnt find the stats of the player usable ships?
Would be very helpful to have the stats in the ship selection screen and as entry in the database.
Default speed, hull, shields
Weapons + loaded ordnance
Warp or jump?

**Comment by aBlueShadow** [comment]
Showing the player ship info at all is a very new addition. According to daid, having it missing in the database is intentional, so I added it to the ship selection screen as a compromise. I am not sure where I should fit in the stats within the available space, and it might well be that the stats are the reason why player ships are not in the DB in the first place (as the vastly different configuration might be confusing)

**Comment by CurePindal** [comment]
> > For newbies its very annoying to handle this lack of important information.
> 
> That's a far too general assumption. Most newbies seem to not be bothered about it at all Of course it could be that this changes now, as more player will become aware of that missing stats, as the player ship infos on the selection screen just make them aware of this.

Excuse me? 2 days ago we had to restart a scenario 8 fking times, because nobody had a clue how the ships are fitted, because for reasons beyond reason daid considers proper information on the ship selection screen not important.

And daid, no, it also not reasonable to assume that proper database entries would be "too confusing". (consider me very baffled)
It doesnt even make any sense. But well, ok, I brought up the issue, but your call.

**Comment by aBlueShadow** [comment]
> Its the first time in decades that a dev tells me that proper information would be too confusing for players...

Maybe no dev told it to you personally, and its not always about confusion, but hiding information from players is really nothing new. Some appreciate it, some hate it. After all, it can be called a design decision. Take FTL for example, were  there is basically the opposite situation. You know exactly how your own ship works, but have only vague information about the enemy. In time, you will get better in learning about new weapons and recognizing them from the visuals, and if it might be better to fight or flee.

> Excuse me? 2 days ago we had to restart a scenario 8 fking times, because nobody had a clue how the ships are fitted, because for reasons beyond reason daid considers proper information on the ship selection screen not important.

Okay, so obviously you are enraged, but swearing and borderline insults are not helpful at all.
IMO your experience does not contradict my statement. "For us it was very anoying" is very different from "For newbies it's very anoying". Because the latter assumes it being true for newbies in general. Which, as I said, does not seem to be the case in my experience. 
Of course it is unfortunate that you and your group had such a bad time playing, but I am still not convinced that knowing more player stats would have turned the tide in your game. The most important thing IMO is to learn about the chain dreadnaught>corvette>frigate>starfighter and knowing which class the own ship is in.
My suspicion is that you ran in a balancing issue with a specific scenario or maybe multiple scenarios. 
Usually it is hardly possible for the scenario makers to do extensive playtests, and some scenarios in general are on the more difficult side sometimes because of balancing issues or missing informations, sometimes intentional. So, a bugreport about those specific scenarios you had problems with might help.
Of course it is still possible that the problem was some confusing or missing information from the game itself but I am struggling to see it was missing player stats. Of course I might be wrong, and if you want to test it, the information is all in scripts/shiptemplates.

Of course you have the right to feel differently about features and the lack of them, but as the issue is now closed anyway, I hope we can move on politely, as ranting about what seemingly isn't going to be changed won't help. So and I hope we can maintain a nice tone and make the best out of the situation.

**Comment by daid** [comment]
Note that I closed this not because I am against the idea, but because my time is to precious to engage with rude people.
