### ISSUE TITLE
REQUEST - Allow font accents

### ISSUE THREAD

**Issue by AstroManu** [daid/EmptyEpsilon#293]
Issue : 
Even if the fonts of the game contain and allow accents, they do not work properly in the game. 

![screen shot 2016-06-07 at 8 08 39 pm](https://cloud.githubusercontent.com/assets/18233357/15878771/a8ced86e-2ceb-11e6-87bd-5301587f2e72.png)

![screen shot 2016-06-07 at 8 03 21 pm](https://cloud.githubusercontent.com/assets/18233357/15878690/14e05bc8-2ceb-11e6-8dd6-46cadb319954.png)

It is also impossible to write accents in the game in the GM screen or communication.

To reproduce : 
- Insert  " à é è ù "  or else in a script that appear in the game. 
- Try to write accents in the game master tweak mode.

**Comment by elptito** [comment]
For information,  It works if you encode the scenario file in Ainsi (not
for GM tweak mode of course)

**Comment by Fouindor** [comment]
I've tinkered a lot with the concept (wanted to do French/Spanish/Russian translations) (https://github.com/daid/EmptyEpsilon/issues/46 , http://bridgesim.net/discussion/155/translation#latest ), without managing to have a solution. (My programming experience is very limited). As of now, the game can not support unicode, and the definition of the strings used seem to be system-dependent.

La communauté française a l'air d'être bien représentée en tout cas ! ;)

**Comment by elptito** [comment]
En effet, il faudrait monter une team francophone ! :) 

I created a french dictionnary (without any accent) for EE and developed a R program to parse the code and translate it. I run it before the compilation and it work well. From now, a word or an expression can only be translate into one word or expression ("Back" could not be "Arrière" and "Retour" at the same time), but It is on my TODO list.

If you are interested, I can share the program and the dictionnary.

**Comment by Fouindor** [comment]
I've tried to use the libintl library to provide on-the-fly translation. It uses the gettext function, which is cross-platform. The basic principle of using this function is that instead of using just the string, you call gettext(string), which will retrieve, if available, the translated string in the set language.

gettext uses automatically a automatically generated word database (from source code), which can be then be translated with a program like poedit (it is much simpler for both programmers and translators). A very good feature of this function is that you can optionally set a context, which allows different translations of a same word. xgettext("back_direction", "Back") and xgettext("back_ship", "Back") for instance.

While the basic premise worked quite elegantly (even if my code was a mess), setting the language was really obscure and did not work well cross-platform. As I want to be able to set the language independently of the system language (in our crew, we have english and spanish speakers on french computers, and thus would like to be able to set their language of preference).

Obviously we're both very interested in this :)
But as of now, I cannot really invest much time in this. Seeing that there is interest in this, I may retry in the weeks to come, using a different library, which is also based on gettext.

**Comment by CaptLapadite** [comment]
Wow, and I though I was the only Frenchy around. 

I'm currently building a scenario for our next event and I plan to translate every communication and database text. I'll try to change the encoding as you proposed elptitot. I'm using Sublime text and here are my choices, which one should I take ? 

![screen shot 2016-06-08 at 9 25 50 am](https://cloud.githubusercontent.com/assets/18233357/15895847/6b131664-2d5b-11e6-88b7-a7c4c15e0d47.png)

We'll create a few scenarios in the current months, in french, to support our activities. 
Allowing the accents in the game would be much apreciated :)

**Comment by Fouindor** [comment]
ISO 8859-1 should be compatible with ANSI (https://en.wikipedia.org/wiki/ISO/IEC_8859-1)

**Comment by elptito** [comment]
I found Windows-1252
(http://stackoverflow.com/questions/701882/what-is-ansi-format)

**Comment by daid** [comment]
But UTF-8 will be the encoding to use if we want to fix this properly. Any other encoding will cause pain one way or another.

I'm no fan of translations of software, which is why you see me being quite silent about this whole part. It's a lot of work, it gets outdated quickly, and the people that say "I will keep the translation up to date" usually disappear within 2 months.

**Comment by elptito** [comment]
Here are my files. It is much more a handwork job than you @Fouindor , but it work ^^

The R script can be launched by any windows or Linux console, you have to change the setwd function at the beginning, with your folder.
The R script load the dict_fr.txt file, and parse into EmptyEpsilon/src folders to change files. When a file is changed, a copy (with .old) is made, to avoid issues.

Some other functions are available in the R script, in order to restore the EE folder, or in order to find expression.

If you want some other explanations, I will be your guest.

[translation.zip](https://github.com/daid/EmptyEpsilon/files/305176/translation.zip)

@daid : Of course, I cannot promise to you that I will keep the game updated, but I want to do this (and I already do this with my R script). And, if we are many translator for a language, I think there is less risk of desertion. At least, if the code could allow font accents, I will help french people a lot

**Comment by Fouindor** [comment]
While I agree this is opening a can of worms, I sincerely believe that it will benefit the project in the long run. Maybe, it can be implemented in two steps : first have the translation framework, and then UTF-8 ?

Anyways, I'm looking forward to trying ^^

**Comment by CaptLapadite** [comment]
Update : encoding the script in "Western (windows 1252)" make accents to show correctly in the database.
Thanks for that !

**Comment by daid** [comment]
@Fouindor I rather first implement UTF-8. The tough part about the translation framework is fixing the string concat that is done everywhere to proper format functions.

**Comment by lacombet** [comment]
Hey guys,

Any update on this issue ?

See you,
Thomas
