### ISSUE TITLE
Suggestion : Forcepae for some configurations

### ISSUE THREAD

**Issue by tdelc** [daid/EmptyEpsilon#397]
Hi,

I am using netboot install and it didn't work for one of my old laptop, but pae is disabled on it. After some research, I add to command forcepae -- forcepae in the config.cfg/defaut file, and now it works perfectly.

I don't know if it is "dangerous" to add this command permanently.

**Comment by daid** [comment]
It's not, we have a thinkpad that requires the same. The problem is that there are a few CPUs that don't report having PAE but actually have PAE support in the CPU.

**Comment by elptito** [comment]
Ah ok, thanks for the explanation, So I keep it in my code.

I know that it's not the same issue, but it refer to the netboot installation : When I try to use config_manager.py, the folder "configs" is not present, I have to add it by myself. So It think it's the same for all and it could be nice to add it during the installation. But I don't see where :)

**Comment by daid** [comment]
There are a few minor errors like this still in the script. Another problem is network booting a 64bit UEFI systems, which fails as that cannot boot a 32bit kernel.

**Comment by daid** [comment]
I want to re-build my server soon, and use this exact script.

**Comment by elptito** [comment]
I have just one more question about netboot : according to you, is it possible to connect a external session of EE into a server made by netboot ?

I want to use a windows desktop in the same network (because I am not able (from now) to configure my DMX device for linux). When I launch the windows session, EE can find the LAN server (so the connection seems to be ok), but when I click on "connect", i try to connect but fails after 10 seconds with this log : [INFO]  GameClient: Failed to connect.

Do you if there a big problem which block the connection or if this is just a parameter I have to change ?

Thanks in advance,

**Comment by daid** [comment]
Well, first you need to make sure you run the same versions of the game.

Also, windows firewall is your enemy here. Windows will identify the network from the netboot environment as a "public network" without telling you, and this will block any incoming connections, ALWAYS, even if you disable windows firewall.
You can change the network type (public/private/office) somewhere in the network settings (depending on your windows version, this has changed every version of windows)

I'm usually running with the server on my windows laptop and the rest network booted, so this can work.
