### ISSUE TITLE
Script error in Birth of the Atlantis

### ISSUE THREAD

**Issue by aBlueShadow** [daid/EmptyEpsilon#487]
When starting the Birth of the Atlantis mission script, the following error appears
`[String "scenario_08_atlantis.lua"]:113:attempt to index a nil value (global 'b20_artifact')`
The game can be started anyway, but the mission does not seem to progress. (No initital message from the station)
It appears to be a bug in the latest change of the script.

**Comment by NinjaSpectre** [comment]
The problem is that b20_artifact:setDescriptions() is referencing values that haven't been set yet.  To fix this move the other b20_artifact properties above that line in the script, in particular the following lines:
b20_artifact.beta_radiation = irandom(1, 10)
b20_artifact.gravity_disruption = irandom(1, 10)
b20_artifact.ionic_phase_shift = irandom(1, 10)
b20_artifact.doppler_instability = irandom(1, 10)
