### ISSUE TITLE
Game crash on connect

### ISSUE THREAD

**Issue by m3nda** [daid/EmptyEpsilon#51]
Hello,
Game is crashing (on client side) when you try to connect via internet. 
We opened and forwarded port 35666 on server (tcp and udp).

Other problem is that u cant play using i.e. tunngle.

**Comment by nallath** [comment]
I don't think we've ever tried playing it over the interwebs. We usually just play over a local network.

**Comment by daid** [comment]
We haven't tried, but there is not a real reason why it should not work. Might be the same crash as https://github.com/daid/SeriousProton/issues/6

**Comment by kwadroke** [comment]
Crash Report from 2015.11.13 build: (ran twice)
https://gist.github.com/kwadroke/dd5ebf388f99daa6bc79

This RPT is from a computer running Windows 8.1 32bit on Intel Atom with Intel HD Graphics card.

I have noticed if you quickly click connect when the server appears, sometimes you can connect without crashing.

**Comment by daid** [comment]
FYI, the intresting part of the crash file is:
```
004EEDCF 3C8F81E9 063B1CA0 0023FB58  EmptyEpsilon.exe!getSystemEffectiveness  [/home/daid/ee/EmptyEpsilon/src/spaceObjects/spaceship.cpp @ 924]
00501A17 3C8F81E9 0067875C 00677FEC  EmptyEpsilon.exe!update  [/home/daid/ee/EmptyEpsilon/src/spaceObjects/cpuShip.cpp @ 70]
00596B02 00000001 06394194 0023FDC4  EmptyEpsilon.exe!runMainLoop  [/home/daid/ee/SeriousProton/src/engine.cpp @ 139]
00638B66 056181A8 00000032 00000001  EmptyEpsilon.exe!main  [/home/daid/ee/EmptyEpsilon/src/main.cpp @ 229]
004013E0 7FFDB000 74E84170 0D731E29  EmptyEpsilon.exe!__tmainCRTStartup  [/build/buildd/mingw-w64-3.1.0/build/i686-w64-mingw32-i686-w64-mingw32-crt/../../mingw-w64-crt/crt/crtexe.c @ 332]
74E84198 7FFDB000 2F451DAD 00000000  KERNEL32.DLL!@BaseThreadInitThunk@12
770332D1 FFFFFFFF 7705F08F 00000000  ntdll.dll!__RtlUserThreadStart
7703329F 004014E0 7FFDB000 00000000  ntdll.dll!__RtlUserThreadStart@8
```
As well as:
```
EmptyEpsilon.exe caused an Access Violation at location 004EEDCF in module EmptyEpsilon.exe Reading from location 000002D5.
```
What it says, is the function "getSystemEffectiveness" on the line "if (gameGlobalInfo->use_system_damage)" is accessing memory that it is not allowed to access. Namely, address "000002D5", which is close to 0. Meaning that "gameGlobalInfo" is not yet set.


Which, now that I think of it, makes total sense. The "gameGlobalInfo" object is send from the server to the client, but ships can be send before this. If there is a large came world, and the network connection is a bit slow. Then ships could be on the clients before the game state is complete, causing this crash. Which also explains why it only happens when there is a scenario selected already.

The fix is also easy!

**Comment by daid** [comment]
Many thanks!
