### ISSUE TITLE
Problem with the name of the sector

### ISSUE THREAD

**Issue by tdelc** [daid/EmptyEpsilon#514]
With the last release, i notice a problem. You can see it when you scroll down the windows starting from the 0,0 coordinate.

Sectors A0 to A99 appear two times in a same row just one after the other.

![image](https://user-images.githubusercontent.com/13868149/34662502-71d5bc04-f451-11e7-8986-8038bac75a92.png)

**Comment by oznogon** [comment]
PR #512 would probably change this behavior.

**Comment by csibbitt** [comment]
"Sectors A0 to A99 appear two times in a same row just one after the other"

Yup. There is a bit more to this issue, too. We started to experiment with larger scale maps and immediately ran into this.

The reported problem is here: https://github.com/daid/EmptyEpsilon/blob/master/src/gameGlobalInfo.cpp#L232

Positive X simply counts up and seems fine for practical use. Negative X counts down from 99 to 0 then into the negatives, so overlaps with the Positive axis immediately and for 100 sectors. 

Here is a screenshot of the existing origin at F5 and the imposter origin, also called F5 - notice the numeric part goes negative instead of to 99 on the imposter
<img src="https://user-images.githubusercontent.com/5091372/146269928-219cf407-af8c-491d-9ecd-c44e57ec35df.png" alt="Old Origin" width="250"/>&nbsp;&nbsp;<img src="https://user-images.githubusercontent.com/5091372/146269982-0de7325c-3b69-4e94-860f-2dc7c95216d4.png" alt="Old Fake Origin" width="250"/>

This appears to have been a stylistic decision (preferring 99 to -1), but really limits the unambiguous play area around the origin.

There are also problems in the Y direction. Positive Y counts up without bound, through the capital letters, then [\]^_` then into lowercase letters and beyond, wrapping around the ascii table making very interesting results. Negative Y counts zz, zy, zw, ... zc, zb, y{, yz, yy, ...

Here is a screenshot of the existing glitches in the North and South
<img src="https://user-images.githubusercontent.com/5091372/146270125-10b1a998-43a8-45a0-85f9-47f6648effe4.png" alt="Old North" width="250"/>&nbsp;&nbsp;<img src="https://user-images.githubusercontent.com/5091372/146270184-05781242-bfa8-49d2-9859-b221196293a5.png" alt="Old South" width="250"/>

I'm about to propose a patch that fixes these glitches without significantly altering the existing scheme. The only major change is the area West of the origin now goes negative immediately instead of counting down from 99, which is necessary to fix the issue of duplicate sectors. The play area used in the scenarios (East of A0 near the origin) is totally unchanged. The patch offers a much larger glitch-free play area with 681 sectors North to aa5, and 697 sectors South to ZZ5.

Here are the new origin , north, and south screenshots:
<img src="https://user-images.githubusercontent.com/5091372/146270237-80f92ba9-3acd-4607-be85-c143a17e4f02.png" alt="New Origin" width="250"/>&nbsp;&nbsp;<img src="https://user-images.githubusercontent.com/5091372/146270248-131192dc-4864-4669-ba3f-1bfeb2d7a538.png" alt="New North" width="250"/>&nbsp;&nbsp;<img src="https://user-images.githubusercontent.com/5091372/146270305-2a566be2-8234-4cdd-b2ec-ec457729d407.png" alt="New South" width="250"/>
