### ISSUE TITLE
Support for cloaking? 

### ISSUE THREAD

**Issue by RayvenMaker** [daid/EmptyEpsilon#547]
@daid Does the cloaking function `ShipTemplate:setCloaking()` even work? What does it do? Is this a planned feature, or has it already been implemented? 

If this hasn't really been implemented, here are some ideas I have: 

1. Cloaking makes the ship invisible to long range scanners. This is pretty balanced--it just allows you to sneak up to ships without them noticing, or escape without a trace. They can still shoot at you. Also, maybe if Science scans that ship while it's within short-range scanners, it can be tracked in long-range radar until the cloaking system is cycled on/off.
OR
2. Cloaking makes the ship unable to be locked on by homing-style missiles. This might be a bit overpowered, so balance it by requiring it to have a warm-up/cool-down, along with using a lot of energy.

I kind of like option 1 better, just because it introduces some new strategies while not being ridiculously overpowered. Let me know your thoughts... I think this would be pretty interesting!

// RayvenMaker

**Comment by daid** [comment]
It doesn't do anything beyond setting a flag on the template. Cloaking was never implemented.

EE started out as a clone of Artemis. Artemis has cloaking. Which is why I added it to the ship templates. But, after playing a few more Artemis sessions, I found cloaking to be flawed (in Artemis) as it came across as a bug, where some stations see a ship, and others don't.

But we can look at two example systems of cloaking in other games. Eve online has some pretty clear rules on Cloaking, https://wiki.eveuniversity.org/Cloaking_101 pretty  much comes down to, you can only fly when cloaked, nothing else. No warping, no weapons. And getting too close to other ships de-cloaks you.
And then there is FTL, where cloaking works completely different, and acts more like a dodge move.


So while cloaking could be interresting for player ships, I don't think it would work very well for the AI ships, as it would come across as bugs instead of a feature.

**Comment by RayvenMaker** [comment]
Oh, I see. Yeah, EVE does have a pretty good cloaking system--what you can do with it is limited, but then again, cloaking can easily be overused. It makes sense that for AI ships, it would look like a bug... hopefully, there's a way we can pull it off without that. I agree, for player ships, it would be pretty fun. Thanks, @daid!

// RayvenMaker

**Comment by RayvenMaker** [comment]
@daid Here's an idea: what if cloaking was more of a radar jammer? Most of the rules that EVE lays out would still apply, but it might not come across as a glitch. 

If a ship is currently is "cloaked", it would appear either as a large, faint blur on the radar display or as a single ship that randomly glitches around the general area that the ship _might_ be. In Helms, Weapons, and Science, if someone attempts to select this ship, it'll show an error saying that this ship is "cloaked". However, in Science, there is an option to run a deep scan (the hard, two-step kind of scan) on that "cloaked" ship. This will give the "jamming frequency" that the cloaked ship is using. Then Science tells this frequency to Relay, who can broadcast a destructive frequency that cancels out the ship's jamming frequency. Once that's done, the ship is completely visible... for as long as Relay keeps on broadcasting that decloaking frequency. Both the process of broadcasting jamming frequencies and broadcasting anti-jamming frequencies would require power and would prevent Relay from doing anything except communicating with other ships. 

If you're trying to cloak your own ship, you simply set your jamming frequency in Relay, and have Relay broadcast that frequency out. 

This would give another job to Relay (which would be nice), as well as show an obvious clue to the players that the ship is actually cloaked, and that it isn't just glitching out. This also retains the tactical advantage of cloaking, because although it's obvious that you're _there_, the enemy has no idea exactly what, where, and who you are. Honestly, I'd love to see this implemented in Empty Epsilon. 

// RayvenMaker
