### ISSUE TITLE
Reactor health could go under 0% and reach negativ value

### ISSUE THREAD

**Issue by Fank** [daid/EmptyEpsilon#583]
Without any punishment.

**Comment by aBlueShadow** [comment]
That's the normal behaviour. Actually, health below 0% causes quite serious problems (or should at least, if this is not the case for you, there might be a bug). First, at 0% and below, the reactor is not working anymore, so the energy generation drops to zero, wich will deplete the battery pretty fast.
Second, if it is below 0% and still falling, the ship is in big danger, because if the reactor health reaches -100%, it will explode.

**Comment by Fank** [comment]
I expected the worst by reaching 0 value, not -100%.
It was just a short situation because some one when stupid and forgot the cooling for the reactor, so i don't know what happened after it exactly.

**Comment by daid** [comment]
Between 0 and 100% systems are functional, between -100 and 0% they are no longer functional.

I did this to make it clear when subsystems are still functional, and no longer work. Will still requiring heavy repairs in some cases.

**Comment by Fank** [comment]
I understand it, but i does not feels right.
But do not have an idea how it could be changed to feel it more natural.
