### ISSUE TITLE
More Event Callbacks for scripting

### ISSUE THREAD

**Issue by czenker** [daid/EmptyEpsilon#587]
After having the event callback for Artifacts introduced in #586 I would like to add more of them.

## 1. What are you missing for your missions?

I'm thinking of 

* ~`SpaceObject` destruction~ #612
* ~`SupplyDrop` pick up~ #611 
* ~`WormHole` when anything jumps~ #587
* ~`ScanProbe` being send~ #735
* ~`ScanProbe` self-destructs~ #735
* ~`Mine` explosion~ #713
* ~`Asteroid` destruction~ fe5eabe99681b938b845768b380c82eb2495014d

Anything else you are missing?

## 2. Naming things

I've been thinking on what naming scheme to use for the Lua API.

* `SpaceObject:setPickUpFunction(function() end)`
* `SpaceObject:setPickUpCallback(function() end)`
* `SpaceObject:onPickUp(function() end)`
* `SpaceObject:onPickUpFunction(function() end)`
* `SpaceObject:onPickUpCallback(function() end)`

Personal I would prefer the third version, because it is brief and all events are in one block in the documentation. Only issue I see is that `onPickUp` could be mistaken for a property rather than a function by a scripter.

What do you think?

**Comment by daid** [comment]
The 3th format is also what I like the most. It reads the most natural.

And as most people look at examples on how to use things, I don't think the mistaking it for a property will be a huge risk.

The reason these callbacks didn't exists before, was because the ScriptSimpleCallback was a pretty late addition to the code. And the older callback mechanism had some serious flaws, so I didn't use it much.

**Comment by amir-arad** [comment]
the 3rd format is used in EE gui elements for the handling of gui events. 
so if in space objects the same naming convention will have close but different semantics, it may be confusing.

I am missing global events for objects creation in this suggestion. something like `onNewSpaceShip(function() end)` where you can hook a function that registers all other relevant hooks for spaceships.

**Comment by czenker** [comment]
I think I'll leave it at these three PRs for now. I don't find the other things mentioned in my opening post not as useful and currently have no plans on using those. But in case anyone finds them useful let me know.

> I am missing global events for objects creation in this suggestion. something like `onNewSpaceShip(function() end)` where you can hook a function that registers all other relevant hooks for spaceships.

I thought about something like that too. But I think having this triggered for SpaceObjects created via scripts is really not practical. You would need to call the `onNewSpaceShip` as soon as a SpaceShip is created via `CpuShip`. But at that point it does not have a template, a faction or a name – so there is not much you could do with it. I think there are ways around it, but when we talk about scripting I do not see how such a callback would be helpful.

But it would make total sense to trigger something like that for the GM console, so scripts can modify GM-created SpaceObjects and include them. This is something I also missed. But I need to check where  such a change would need to be mode.

**Comment by daid** [comment]
We could do a onNewSpaceship 1 update() after it was created, that would ensure everything is set. Not sure what the exact use case it. But that would make it workable.

**Comment by amir-arad** [comment]
Maybe after `applyTemplateValues` then.
The use case is more principal - to extend the behavior of objects in the map using callback behavior, one needs to attach callbacks to all objects created in the map. game objects are created in one of four ways: 
 - the map logic
 - the http API
 - GM 'create' action
 - CPP code (for example drones in my "drones and cargo" feature branch)
since some of these places are agnostic to map logic (and that's a good thing) I think it's better if the behavior extension has a place to register statically, so it is applied no matter the means that created the game object.

**Comment by oznogon** [comment]
PR #713 implements `Mine` explosion callbacks in the same manner as `SpaceObject`, right down to returning the instigator (mine layer) if it has one.

In a second iteration, it could also be handy to return the entity that triggered the explosion, but I think that would require either a separate callback (onCollision?) or refactoring `Mine` more broadly.

**Comment by oznogon** [comment]
fe5eabe99681b938b845768b380c82eb2495014d exposes the `onDestroyed()` callback on SpaceObjects, which should encompass all other object types that don't have a specific callback.

**Comment by czenker** [comment]
Thanks @oznogon for finishing the remaining items in the issue!
