### ISSUE TITLE
Feature Request: Enable numeric keypad in IP address field

### ISSUE THREAD

**Issue by pixelclef** [daid/EmptyEpsilon#625]
A lot of my fellow players are quite adept at using the numeric keypad.

**Comment by aBlueShadow** [comment]
Are you talking about the field when pressing "Start client"?
I just tried it out, and numpad works just finde here, both with the linux version as well as the windows version in WINE, can't test it on a windows machine right now.
Have you double checked if the numpad was turned on on your keyboard?

**Comment by Xansta** [comment]
Did the dot on the numeric keypad also work along with the digits? I think it's the dot that does not work. The digits work just fine.

**Comment by aBlueShadow** [comment]
Interesting.. I thought this was due to my german keybard layout (in german, comma is used as decimal separator) but even on a us-layout, it doeasn't work in EE. However, I doubt there is an easy fix to this, as the dot key on a numpad seems to be a tricky thing: I have done some research and there seem to be problems to get it to work even if en-us layout is activated (had the same problem: I so I ran a live-cd to let that key produce a "." in the normal system, so I could check if id did work in EE then, but it did not)
...
### However, there is a fix using xmodmap:
set up a local Xmodmap file
`xmodmap -pke`
This copies the whole xmodmap system file. Now edit .Xmodmap and search for keycode 91, the numpad Separator Key.
That line probably has entries like **KP_Separator**. Replace these by **period**
If you don't plan to do further modifications, you could of course delete any other line.
After a restart or doing manually `xmodmap ~/.Xmodmap`, that key should produce reliably a period, and also will work in EE.


My guess is, that KP_Seperator depends on the system language, not the keyboard layout language, and that EE/SFML don't accept that key symbol, at least not as a period.

**Comment by Xansta** [comment]
Does Xmodmap work for Linux, Windows and Mac (even if EE runs under WINE on Mac)? I've got users with machines of all these types.

**Comment by aBlueShadow** [comment]
Probably only for Linux and other systems that are using X11, is this problem present on all plattforms? On the other systems there are probably other methods to remap keys.

**Comment by Xansta** [comment]
I just tried it on a Windows machine (because it's what's in front of me) and the dot/decimal/separator key on the numeric keypad does not work. I don't usually use the numeric keypad, so I'd have to remember to try it on the other machines next time I get on them for an EE game. I'll definitely try the workaround for the Linux boxes.

**Comment by techfreek** [comment]
I looked into this because I was noticing it too, based on some digging, this is an issue in sfml: https://en.sfml-dev.org/forums/index.php?topic=18861.0 which lead me to the actual source of sfml and it's not even mapped: https://github.com/SFML/SFML/blob/489482a630c5286e488ffc270c10562809056d8e/src/SFML/Window/Unix/InputImpl.cpp

**Comment by daid** [comment]
Indeed, this is a huge issue in SFML, keyboard mapping is just messed up for edge cases like the numpad.

SDL2 does this proper (except for the emscripten version, but I submitted a patch for that), but switching all the code to SDL2 would be a major undertaking. (My followup game engine SeriousProton2 uses SDL2 and a lot of other things I learned from building EE. But has a few incompatibilities that makes switching to it break scenario scripts for example)

**Comment by MyrddinE** [comment]
It's an *ooooooold *issue <https://github.com/SFML/SFML/issues/7> with SFML.

**Comment by daid** [comment]
Well, that issue goes into a lot of smaller detailed issues, and is like one massive issue for a whole class of problems.

I fixed a issue like it for SDL2 emscripten: https://github.com/emscripten-ports/SDL2/pull/95
But by having 2 other versions of the implementation that I could check for expected behavior, and limiting myself to a subset of the problem, the fix was doable. In SFML, I don't even think they agree on what the fix should be.

**Comment by MyrddinE** [comment]
The basic issue, not catching all the unique keys on the keyboard that
people can press, is pretty sad. I'd be fine if they caught a key but
couldn't render it to a text box... the biggest issue is being unable to
map keys properly on all the keys on your keyboard. It's not a complicated
issue.

Translating and rendering text from the keypress is harder, but they can
support games without supporting text. I find it stupid that they haven't
fixed the more important, easier issue for eight years.

**Comment by oznogon** [comment]
SFML/SFML#1596, specifically about the dot key, was closed without a resolution. The 1596 ticket was linked to SFML/SFML#1596, a more than four-year-old PR to convert keyboard input to use scancodes.

**Comment by gcask** [comment]
Seems the same as #195 (... and also seem virtually unsolvable 😞 )
