### ISSUE TITLE
Add transparency to model

### ISSUE THREAD

**Issue by tdelc** [daid/EmptyEpsilon#647]
Hi,

I tried to add a option in the gm screen to change the transparency of a ship (in order to allow a ship to be hide). From now, i have a bool variable to show the model or not, but i fail with the transparency setting.

I saw that glColor4f function allows to add transparency, but when i add this function in the model_info file, nothing append.

Does someone has a advice to this ?

**Comment by daid** [comment]
Rendering of the 3D viewports happens in 2 passes, first all "solid" models are rendered, and then transparent things are rendered on top of that. This has to do with depth buffer issues. Also, the objects are rendered back to front for this reason.
Example of issue otherwise:
https://gamedev.stackexchange.com/questions/68957/order-of-render-with-transparency-opengl


For the game code, this means that every object has 2 render functions:
https://github.com/daid/EmptyEpsilon/blob/master/src/spaceObjects/spaceObject.h#L164
"draw3D" and "draw3DTransparent"

for spaceships, draw3D is used to draw the ship model, and draw3DTransparent is used for shields hit effects and the warp overlay.

Next to that, the OpenGL shader also has influence on how the "alpha" component is passed.  For example, the shaders used for spaceship rendering ignore the alpha value from textures. And only use the one set by glColor4.

The whole 3D rendering part of EE is quite complex. So making a ship transparent isn't as simple as flipping a switch. (just for extra frustration. In the SeriousProton2 engine, it is a simple switch from normal to transparent rendering)

**Comment by tdelc** [comment]
Thanks for the advices ! I think I have a solution : 

In the file model_data.lua in the function render()

add 
```
glEnable(GL_BLEND);
glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
```
at the beginning of the function, folllowing by 
`glColor4f(1.0,1.0,1.0,alpha);`
and 
`glDisable(GL_BLEND);`
after the rendering.

By changing the value of alpha, I succeed to change the transparency of the model. Do you think there is a problem with this code ? I will try now to provide alpha as a parameter of the function to use it via script or via GM.

**Comment by daid** [comment]
There won't be any huge issues, performance wise the impact is minimal. You might get some rendering artifacts if two invisible ships are behind each other. And you'll most likely notice some "odd" behaviour in the rendering of a single ship model as well, where some parts occlude each other and other parts don't.


But I don't think I'll accept it as a patch, if that is your end goal. For the simple reason that draw3D should draw solids and draw3Dtransparent should draw transparent things.

**Comment by tdelc** [comment]
Ok, thanks one again for the advices, I will test it and keep it in my fork.
