### ISSUE TITLE
Bug with netboot

### ISSUE THREAD

**Issue by tdelc** [daid/EmptyEpsilon#680]
Hi daid,

I have a huge problem with your netboot system. Usually, all is alright, but now, with 5 new computers, the display does not work. The log says : Failed to open x11 display, make sur the display environment vatiable is set correctly

Do you have any advice for me ?

Of course, my larp is tomorrow, and now, 20 computers are fine, but not the last bridge...

**Comment by daid** [comment]
Sounds like a driver issue. Do those machines work if you run a normal debian/ubuntu install (or live CD)?

Updating to stretch instead of jessie might also fix the issue. Or maybe you need an extra debian package containing the proper drivers for the GPUs in those machines

**Comment by tdelc** [comment]
Ok, so no change into your code but in the debian system. I cannot run anything into these machines (no hard disk, no live cd...), but I can add an extra debian package containing some extra drivers.  Do you know how I can know what drivers I need ? I never updating the debian server since... long time ago, maybe this could help. So could you please explain me how to update the netboot system (I think I understand that updating the debian is not necessery but I need to update via chroot or something like that ?

**Comment by daid** [comment]
I wouldn't try updating the netboot from jessie to stretch, but build a new root.

Backup the /srv/nfsroot and /srv/tftp folders, and then use the https://github.com/daid/EmptyEpsilon/blob/master/netboot/build_netboot_system.sh script again to build a new set, but with "jessie" replaced with "stretch".

However, no garantee that that is the actual issue. I do know the issue is linux related. As your time to the larp is limited, I would recommend grabbing USB drive and see if the ubuntu live USB works: https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-windows

If that does not provide graphical output, then the issue is much bigger. If it does provide graphical output, you do have starting point that works.

**Comment by tdelc** [comment]
At least, if the strech version doesn't work more (or, worse, disabled the rest...), I will just have to restore these two folder, and all will be back ? (it is not a problem to do the test, even for nothing, but I don't want to crash everything...)
I will also try the usb stick method.

Thank a lot for the help.

**Comment by daid** [comment]
Yes, just restore the 2 folders and you are back. That's why I said to back them up.

**Comment by daid** [comment]
Did you manage to get it to work? I wouldn't mind knowing what the issue was
