### ISSUE TITLE
Engineering and Security Crew (Suggestion)

### ISSUE THREAD

**Issue by Fouindor** [daid/EmptyEpsilon#88]
Hello,
I've wanted to make part of a few suggestions about crew management, which I suggest I can implement gradually :

:arrow_forward: Have an engineering crew variable (engineering_crew_max, engineering_crew). This number would influence system reparation rate, based on ship size (so reparation rate would be proportional to engineering_crew/size), which would make sense to me (you'll need more engineers to fix a big ship).

:arrow_forward: Make possible that when fired upon, crew can be wounded (increment a engineering_crew_wounded) or killed (decrement the engineering crew) on hull damage.

:arrow_forward: Add an new system, the Medical Bay, which regenerate wounded crew (decrement wounded crew variable) on a rate proportional to system power.

:arrow_forward: Add security crew variables (which would pave the way for boarding)

What do you think ?

**Comment by daid** [comment]
Someone has been playing FTL? ;-)

**Comment by Wrongtown** [comment]
Yeah I'm personally not a big fan of the Security Crew/Boarding feature with the current stations as Engineering can feel pretty beleaguered as it is. Mind you, the possibility of having more than 3 crew might alleviate that a little. 

I can see the fun, I guess Relay would be a prime contender for managing that stuff? Though really if security was implemented I'd probably vote for a separate station and have the possibility of being boarded/crew injuries optional in the same way that system damage is optional.

**Comment by Fouindor** [comment]
What I envisioned for now is just numbers for crew, engineering or otherwise. You would still have 3 DAMCON teams, but their effectiveness would be proportional to (crew_number/ship_size). So running out of engineering crew (everyone wounded or dead) would still leave you with 3 DAMCON teams, but they would repair nothing.

**Comment by nallath** [comment]
Well, adding some extra crew to relay would be interesting right? He could have a certain pool of extra people that he could send to different parts of the ship (eg; Add a few people to loading weapons?)

**Comment by Wrongtown** [comment]
Yeah I guess I'm a bit wary of leaving engineering with NO ability to repair anything... 

If the "Medical Bay" is broken and you're out of engineering crew to fix it (repair rate = 0), then it becomes quite easy to become stranded. Though your ship isn't dead and at very least the Engineering Officer is living, you can't carry out any repairs. I would say the minimum rate of repairs shouldn't ever drop to 0.

I'm a little concerned that relay could end up spending all their time bossing crew about to the detriment of their probing/communication duties.

**Comment by daid** [comment]
Improved docking would help on this. If you are docked to a station, you can ask the station to provide medical care for your crew. Thus allowing for repairs after that.

The odd bit if, if you have no engineering crew left, what to do with the crew "people" walking around in the engineering screen?

**Comment by Wrongtown** [comment]
What I'm thinking is where you can't actually limp back to a station. Forgive my crappy pseudo-code but:

IF Repair_Rate = 0 
AND Medbay_Heal_Rate = 0 
AND (Reactor OR Impulse Engine OR Maneuvering) = 0
THEN FUBAR = 1

Which is why I say that engineering should always have just a LITTLE bit of ability to repair systems, even if it's basically something like the [Red Dwarf Skutters](http://reddwarf.wikia.com/wiki/Skutters). I think there's a huge difference in the fun of an obviously hopeless situation vs a really terrible one with just a tiny sliver of hope.

True about the sprites wandering around but doing nothing, it doesn't really make sense in the "narrative" presented by the game. It would make more sense to actually have the number of DAMCON teams presented on the map go up and down. Maybe even arrange it so if all DAMCON crew are killed all sprites go away and are replaced by a single emergency utility robot for Engineering to set to work as they weep into their console?

**Comment by Fouindor** [comment]
Or maybe set the minimum DAMCON crew to 1 :)

**Comment by nallath** [comment]
Or you always have 3 damcon crews with atleast one guy in it. The rest are red-shirts so they are prone to being killed all the friggin time ;)

**Comment by Fouindor** [comment]
This is maybe the best solution. I will look into that maybe later today.

**Comment by Wrongtown** [comment]
:+1:
