### ISSUE TITLE
fail to build with mingw and LTO

### ISSUE THREAD

**Issue by StarryWisdom** [daid/EmptyEpsilon#910]
bcbf8fbb23709a774bd3e3f66861a51b2f507590 seems to revert the fix in fc4cff5330011a43ced1b71dc22793aed46321f6

The bug there was a failure to build via mingw in WSL, with a large amount of errors (100s/1000s) along the lines of /usr/bin/i686-w64-mingw32-ld: beamEffect.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN10BeamEffectD0Ev[__ZTv0_n12_N10BeamEffectD0Ev]+0x0): multiple definition of `non-virtual thunk to BeamEffect::~BeamEffect()'; threatLevelEstimate.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZN10BeamEffectD0Ev[__ZThn16_N10BeamEffectD0Ev]+0x0): first defined here

I still dont really understand what the original bug was/is, to summarise what I found when fc4c was created.
Its related to LTO being enabled (without LTO it compiles correctly).
The current debian install created by WSL exhibits this bug.
The version daid was using at that time was working.
Daid was able to reproduce the fail to build, but I cant recall if that was via WSL or a linux install.
I dont understand why if it is invalid C++ it is (but would love it explained)
I also do not have a minimal reproduction of the error, it seems to be related to diagonal inheritance though (adding/removing vtable entries masked or showed it), if it is a compiler bug it would be nice to know its in an upstream bug tracker somewhere

**Comment by oznogon** [comment]
Are you using the compiler flag `-flto-partition=1to1`? (If not, can you try with that?)

https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-flto-873

> Specify the partitioning algorithm used by the link-time optimizer. The value is either ‘1to1’ to specify a partitioning mirroring the original source files or ‘balanced’ to specify partitioning into equally sized chunks (whenever possible) or ‘max’ to create new partition for every symbol where possible.

**Comment by JonathanILevi** [comment]
#907 is that pull which appears to have reverted the fix.

I am not able to test; but it looks like WSL is needing the deconstructors to be explicitly defined.  #907 changed the virtual deconstructors to use `= default` (which may or may not be a problem for WSL).  #907 also removed the empty deconstructors, because, you know, they are not necessary... but by the looks of it, when building on WSL, they are.

@StarryWisdom Can you test this?

**Comment by oznogon** [comment]
I cite `1to1` because of the error message:

```
beamEffect.cpp.obj (symbol from plugin):
(.gnu.linkonce.t._ZN10BeamEffectD0Ev[__ZTv0_n12_N10BeamEffectD0Ev]+0x0):
multiple definition of `non-virtual thunk to BeamEffect::~BeamEffect()'; 
threatLevelEstimate.cpp.obj (symbol from plugin):
(.gnu.linkonce.t._ZN10BeamEffectD0Ev[__ZThn16_N10BeamEffectD0Ev]+0x0): first defined here
```

Emphasis on the compiler claiming the destructor is defined first in `threatLevelEstimate` (which includes the `beamEffect` header). My understanding is that LTO reorders the source during partitioning, which can cause header-defined destructors to be (erroneously?) caught as duplicates via include. I'm also guessing that effectively moving the destructor definition into the header in #907 contributed to MinGW (and for whatever reason only MinGW) complaining about it.

I'd expect `lto-partition=1to1` to revert that behavior to something closer to compiling without LTO. cf. https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/?limit=250&viewmonth=201505&viewday=21

**Comment by daid** [comment]
Note that it's really odd, and I'm still assuming compiler bug. As it only happens with the ubuntu version of mingw in WSL. I have debian with WSL, no problems. And my linux build server also has no issues when building with mingw. (Also debian)

**Comment by StarryWisdom** [comment]
testing with -flto-partition=1to1 still has the same fail to build

I am somewhat unsure what JonathanI wanted me to test - I think it is related to the virtual deconstructors, and the other changes in the patch are fine

the WSL I have set up that is causing issues is debian - so I suspect the issue is version based, my WSL install is an up to date buster (mingw 6.0.0-3 , I'm unsure if that is the package that is relevent though, as I dont know where the linker lives)

**Comment by JonathanILevi** [comment]
@StarryWisdom try adding back the deconstructors, removed in #907.

**Comment by daid** [comment]
The mingw package is just a collection of other packages, the important one is most likely binutils-mingw-w64-i686. I have version 2.31.1-11+8.3 and that works.

**Comment by StarryWisdom** [comment]
on the machine that fails to build I have binutils-mingw-w64-i686 2.31.1-11+8.3 as well, so I dont really know whats different
the deconstructors being omitted results in build failures, as does having them expicitly be defaulted
pull request #931 is what I think is a minimal fix locally
